export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CREATOR = 'DELETE_CREATOR';
export const START_LOADING_CAT = 'START_LOADING_CAT'
export const END_LOADING_CAT = 'END_LOADING_CAT'
export const START_CREAT_CAT = 'START_CREAT_CAT'
export const END_CREAT_CAT = 'END_CREAT_CAT'

export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const START_LOADING_PROD = 'START_LOADING_PROD'
export const END_LOADING_PROD = 'END_LOADING_PROD'
export const START_CRUD_PROD = 'START_CRUD_PROD'
export const END_CRUD_PROD = 'END_CRUD_PROD'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID'
export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER';
export const START_LOADING_USERS = 'START_LOADING_USERS'
export const END_LOADING_USERS = 'END_LOADING_USERS'
export const START_CRUD_USER = 'START_CRUD_USER'
export const END_CRUD_USER = 'END_CRUD_USER'

//export const FETCH_PRODUCT = 'FETCH_PRODUCT'
//export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID'
export const CREATE_CART = 'CREATE_CART'
export const GET_CART_BY_USERID = 'GET_CART_BY_USERID'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART';
export const UPDATE_ORDER_ITEM_Q = 'UPDATE_ORDER_ITEM_Q';

export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_ERROR_RESET = `AUTH_ERROR_RESET`
export const AUTH_START_LOADING = `AUTH_START_LOADING`
export const AUTH_END_LOADING = `AUTH_END_LOADING`
export const AUTH = 'AUTH'

